### ISSUE TITLE
CodingErrorFound

### ISSUE THREAD

**Issue by gudeqing** [YangLab/CLEAR#15]
Hi，when I try to run the command 'clear_quant -h", an error raised as following:
Traceback (most recent call last):
  File "/data/users/dqgu/anaconda3/bin/clear_quant", line 11, in <module>
    load_entry_point('CLEAR==1.0.1', 'console_scripts', 'clear_quant')()
  File "/data/users/dqgu/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/users/dqgu/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/data/users/dqgu/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/data/users/dqgu/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/users/dqgu/anaconda3/lib/python3.7/site-packages/CLEAR-1.0.1-py3.7.egg/src/run.py", line 178
    DEVNULL = open(os.devnull, 'wb')
                                   ^
TabError: inconsistent use of tabs and spaces in indentation

Best wishes!

**Comment by xingma** [comment]
Thanks for your reminding! I have fixed this problem.
