### ISSUE TITLE
tophat fusion error

### ISSUE THREAD

**Issue by sharmi85** [YangLab/CLEAR#16]
I have installed all the bowtie, tophat and samtool packages recommended for the tophatfusion run, but getting this error, it cant locate my samtools. I have version you have asked to install...Kindly help

Beginning TopHat run (v2.0.12)
-----------------------------------------------
[2021-01-09 16:21:33] Checking for Bowtie
		  Bowtie version:	 1.0.0.0
[2021-01-09 16:21:33] Checking for Samtools
Traceback (most recent call last):
  File "/userdata/sharmishtha/tools/tophat-2.0.12.Linux_x86_64/tophat", line 4087, in <module>
    sys.exit(main())
  File "/userdata/sharmishtha/tools/tophat-2.0.12.Linux_x86_64/tophat", line 3885, in main
    check_samtools()
  File "/userdata/sharmishtha/tools/tophat-2.0.12.Linux_x86_64/tophat", line 1559, in check_samtools
    samtools_version_str, samtools_version_arr = get_samtools_version()
  File "/userdata/sharmishtha/tools/tophat-2.0.12.Linux_x86_64/tophat", line 1541, in get_samtools_version
    samtools_version_arr = [int(version_match.group(x)) for x in [1,2,3]]
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by sharmi85** [comment]
I have the following versions 
tophat2：tophat-2.0.12.Linux_x86_64
samtools：0.1.18.0
bowtie：1.0.0.0

**Comment by bio-visualisation** [comment]
> 
> 
> I have the following versions
> tophat2：tophat-2.0.12.Linux_x86_64
> samtools：0.1.18.0
> bowtie：1.0.0.0

I used tophat 2.1.0 along with python 2.7 , samtools- 0.1.18 and bowtie- 1.0.0 ; It worked for me. I encountered tophat fusion error with other version of tophat2. Hope this helps.

**Comment by HowardChen330** [comment]
> I have the following versions tophat2：tophat-2.0.12.Linux_x86_64 samtools：0.1.18.0 bowtie：1.0.0.0

May I ask how long one of your samples ran? One of my samples, 'long_spanning_r', has been running this step for more than twenty hours.
