### ISSUE TITLE
TypeError when Running CLEAR: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by JerryZhang-1222** [YangLab/CLEAR#18]
hello! First thanks a lot for providing a fantanstic tool for circRNA analysis!
I have an issue when running circ_quant, the nohup.out file says that: **TypeError: 'NoneType' object is not iterable.** 

**Here is the log file:**
> ###Parameters:
> Namespace(bam='/home/zhangfy/data_projects/RNAseq/LW_MPP/sambamfiles/C-1.sam.sorted.bam', circ='/home/zhangfy/data_projects/RNAseq/LW_MPP/circ_RNA_proj/4_annotate/C-1_circularRNA_known.txt', length=False, output='C-1_quant.txt', ratio=1, ref='/home/zhangfy/data_projects/RNAseq/LW_MPP/circ_RNA_proj/4_annotate/Rattus.genepred', threshold=1, tmp=True)
> ###Parameters
> genePredToGtf is required for maximal isoform selection!
> ###Parameters:
> Namespace(bam='/home/zhangfy/data_projects/RNAseq/LW_MPP/sambamfiles/C-1.sam.sorted.bam', circ='/home/zhangfy/data_projects/RNAseq/LW_MPP/circ_RNA_proj/4_annotate/C-1_circularRNA_known.txt', length=False, output='C-1_quant.txt', ratio=1, ref='/home/zhangfy/data_projects/RNAseq/LW_MPP/circ_RNA_proj/4_annotate/Rattus.genepred', threshold=1, tmp=True)
> ###Parameters
> Traceback (most recent call last):
>   File "/home/zhangfy/miniconda3/envs/RNAseq/bin/circ_quant", line 11, in <module>
>     load_entry_point('CLEAR==1.0.1', 'console_scripts', 'circ_quant')()
>   File "/home/zhangfy/miniconda3/envs/RNAseq/lib/python3.6/site-packages/CLEAR-1.0.1-py3.6.egg/src/circ_quant.py", line 334, in main
>     spReads.extract(extract_args)
>   File "/home/zhangfy/miniconda3/envs/RNAseq/lib/python3.6/site-packages/CLEAR-1.0.1-py3.6.egg/src/spReads.py", line 83, in extract
>     cigar = getCigar(read)
>   File "/home/zhangfy/miniconda3/envs/RNAseq/lib/python3.6/site-packages/CLEAR-1.0.1-py3.6.egg/src/spReads.py", line 30, in getCigar
>     cigar = [ (num2op[num], length) for num, length in read.cigartuples]
> TypeError: 'NoneType' object is not iterable

**And this is my code:**
```
nohup circ_quant -c /home/zhangfy/data_projects/RNAseq/LW_MPP/circ_RNA_proj/4_annotate/C-1_circularRNA_known.txt \
-b /home/zhangfy/data_projects/RNAseq/LW_MPP/sambamfiles/C-1.sam.sorted.bam \
-t \
-r /home/zhangfy/data_projects/RNAseq/LW_MPP/circ_RNA_proj/4_annotate/Rattus.genepred \
-o C-1_quant.txt &
```

C-1_circularRNA_known.txt  is the output file of CIRCExplorer2 annotate
C-1.sam.sorted.bam is the bam file of one sample. I have used samtools sort and samtools index to get this bam file
Rattus.genepred is the genepred file

Thanks a lot!
Zhangfy

**Comment by JerryZhang-1222** [comment]
also, I have installed genePredToGtf but it still told me that "genePredToGtf is required for maximal isoform selection!". I'm quite confused. Thanks!
