### ISSUE TITLE
IOError: [Errno 2] No such file or directory: circ/genePred.tmp

### ISSUE THREAD

**Issue by lssb** [YangLab/CLEAR#20]
Hi,
    Thanks for CLEAR. 
    I am in troubles using CLEAR and looking for solutions. I need your help and this is the error log.

```bash
###Parameters:
Namespace(bowtie1='/home/ionadmin/likun/13SequencingData/00.ref/GRCh38_bowtie_index/GCA_000001405.15_GRCh38_no_alt_analysis_set', genome='/home/ionadmin/likun/13SequencingData/00.ref/02.circ/hg38.fa', gtf='/home/ionadmin/likun/13SequencingData/00.ref/gencode.v39.annotation.gff3', hisat='/home/ionadmin/likun/13SequencingData/00.ref/grch38_snp_tran/genome_snp_tran', m1='temp/test.r1.fq', m2='temp/test.r2.fq', output='04.circRNA/test', thread='8')
###Parameters

###Start hisat2 mapping
# start to get sp sites for hisat mapping
# start to align to genome by hisat
# get mapped and unmapped reads
# sort bam file
# index bam file
###End hisat2 mapping


###Start tophat-fusion mapping
###End tophat-fusion mapping


###Start circRNA annotation
Traceback (most recent call last):
  File "/results/likun/13SequencingData/.snakemake/conda/11a4808895ed45c4508ebd2a16b6e45c/bin/clear_quant", line 11, in <module>
    load_entry_point('CLEAR==1.0.1', 'console_scripts', 'clear_quant')()
  File "/results/likun/13SequencingData/.snakemake/conda/11a4808895ed45c4508ebd2a16b6e45c/lib/python2.7/site-packages/CLEAR-1.0.1-py2.7.egg/src/run.py", line 269, in main
    args.genome, args.gtf, circ_dir)
  File "/results/likun/13SequencingData/.snakemake/conda/11a4808895ed45c4508ebd2a16b6e45c/lib/python2.7/site-packages/CLEAR-1.0.1-py2.7.egg/src/run.py", line 181, in circ_annot
    with open('{}/genePred.tmp'.format(circ_dir), 'r') as inf,\
IOError: [Errno 2] No such file or directory: '04.circRNA/test/circ/genePred.tmp'

```

**Comment by jennynuyirs** [comment]
Hi Issb, 
I'm having the exact same problem as you are with CLEAR, and I was wondering if you were ever able to find out what was causing the issue. I'm not sure where the error could be coming from; the CLEAR source code shows the .tmp file being made so I'm not sure why it can't be found.

**Comment by jennynuyirs** [comment]
It turns out the problem was that the I had the wrong versions of GenePredtoGTF/GTFtoGenePred installed. I specifically had to run the follow commands in my anaconda environment to get the pipeline to work:

```
conda install -c bioconda ucsc-genepredtogtf=366 
conda install -c bioconda ucsc-gtftogenepred=366 
```

**Comment by qmeng14** [comment]
> It turns out the problem was that the I had the wrong versions of GenePredtoGTF/GTFtoGenePred installed. I specifically had to run the follow commands in my anaconda environment to get the pipeline to work:
> 
> ```
> conda install -c bioconda ucsc-genepredtogtf=366 
> conda install -c bioconda ucsc-gtftogenepred=366 
> ```

I did install the version of these genepredtogtf and gtftogenepred, however, still the genePred.tmp not generated, I am not sure, why it could not be found. Many thanks for helping.

**Comment by kizliupei** [comment]
You can try directly convert your gtf to genePred refFlat format using command: "gtfToGenePred -genePredExt -geneNameAsName2 genes.gtf refFlat.tmp.txt". If you get error like "gtfToGenePred: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory" , just use conda to update package "ucsc-genepredtogtf" and "ucsc-gtftogenepred"
