### ISSUE TITLE
Error in run clear_quant when "start tophat-fusion mapping"

### ISSUE THREAD

**Issue by Scathacheng** [YangLab/CLEAR#3]
Hi.
Here is the bug,
Traceback (most recent call last):
  File "/zs32/home/jcdai/zouhan/ChIP/miniconda2/bin/clear_quant", line 9, in <module>
    load_entry_point('CLEAR==1.0.0', 'console_scripts', 'clear_quant')()
  File "build/bdist.linux-x86_64/egg/src/run.py", line 256, in main
  File "build/bdist.linux-x86_64/egg/src/run.py", line 159, in fusion_align
  File "/zs32/home/jcdai/zouhan/ChIP/miniconda2/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['tophat2', '-o', '/hw2600/JcDai/02ChineseBrain/01CLEAR/fusion', '-p', '5', '--fusion-search', '--keep-fasta-order', '--bowtie1', '--no-coverage-search', '/zs32/home/jcdai/04circRNA/03database/bowtie1hg38index/hg38.bowtie1_index', '/hw2600/JcDai/02ChineseBrain/01CLEAR/hisat/unmapped.fq']' returned non-zero exit status 1

I think the problem is that unmapped.fq have no map with index. How do you have any idea to solve this problem?
thanks!

**Comment by xingma** [comment]
It may be related to compatibility of different tools. bowtie (v0.12.9), tophat2 (v2.0.12) and hisat2 (v2.0.5) works well. You may try these versions.
